server:
  port: ${TWEET_WRITE_SERVER_PORT} #8090

spring:
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
  datasource:
    url: ${TWEET_WRITE_ORACLE_DB_URL} #jdbc:oracle:thin:@localhost:1521/freepdb1
    username: ${TWEET_WRITE_ORACLE_DB_USERNAME} #tweetDb
    password: ${TWEET_WRITE_ORACLE_DB_PASSWORD} #pwd

  kafka:
    bootstrap-servers: ${TWEET_WRITE_KAFKA_BOOTSTRAP_URL} #localhost:19092

tweet-write-svc:
  kafka:
    topic: ${TWEET_WRITE_KAFKA_TOPIC} # tweet
