name: Tweet Write Service Build and Docker Push

on:
  push:
    paths:
      - 'tweet-write-service/**'  # Adjust the path to the microservice folder

jobs:     
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: rashm1n/twttrr-tweet-write-service
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./tweet-write-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
